resources:
- name: concourse-repo
  type: git
  icon: github
  source:
    uri: https://github.com/Imvarsh07/concourse
    branch: main
- name: dest-registry
  source:
    aws_access_key_id: ((concourse-aws-access-key-id))
    aws_secret_access_key: ((concourse-aws-secret-access-key))
    repository: 965106989073.dkr.ecr.us-west-2.amazonaws.com/adl-uncertified
  type: docker-image
- name: image-version 
  source:
    access_key_id: ((concourse-aws-access-key-id))
    bucket: com.aqfer.preprod.tmp
    driver: s3
    initial_version: 1.0.0
    key: tst/version  
    region_name: us-west-2
    secret_access_key: ((concourse-aws-secret-access-key))
  type: semver 
jobs:
- name: build-hello-world
  plan:
    - get: image-version
      params: {bump: minor}
    - put: image-version
      params: {file: image-version/version}
    
    - get: concourse-repo
    - task: create-build-atrifacts
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: 
            repository: golang
        inputs:
        - name: concourse-repo
        outputs:
        - name: artifacts
        - name: tags
        run:
          path: /bin/sh
          args:
                - -c
                - |
                  WD=`pwd`
                  cp ${WD}/concourse-repo/Dockerfiles/Dockerfile ${WD}/artifacts/
                  cd ${WD}/concourse-repo/golang
                  go build -o hello
                  cp hello ${WD}/artifacts/
                  
    - put: dest-registry
      inputs: 
      - artifacts
      - tags
      params:
        build: artifacts
        tag_file: image-version/version
        tag_prefix: golang-hello
      

                  
