resources:
- name: concourse-repo
  type: git
  icon: github
  source:
    uri: https://github.com/Imvarsh07/concourse
    branch: main
jobs:
- name: build-hello-world
  plan:
    - get: concourse-repo
    - task: create-build-atrifacts
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: 
            repository: busybox
        inputs:
        - name: concourse-repo
        run:
          path: /bin/sh
          args:
                - -c
                - |
                  ls -l concourse-repo
